# Generated by Django 3.1 on 2020-11-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PictureModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_info',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
